### ISSUE TITLE
It can't be applied to images

### ISSUE THREAD

**Issue by CostinTanasoiu** [ThrivingKings/Badger#7]
It seems that if I try to add a badge to one of my images, it will not work. It actually treats the _img_ tag as if it were a _div_, trying to add content to it.

**Comment by ThrivingKings** [comment]
Sorry about that but please see the readme— this is outdated and is no longer being supported

**Comment by CostinTanasoiu** [comment]
Oh, alright. I don't know how I missed that... Thanks anyway! :+1:

**Comment by ThrivingKings** [comment]
No problem. You could try putting the image inside of a `div` and using badger on that. Not sure if it's the solution your looking for but it may get you close to what you want. Again though, it's an unsupported library so I'd be wary of using it in production environments.
